# 上市公司營業收入統計表（月營收-次月10號公佈）

* 至 [公開資訊觀測站：彙總報表/營運概況/每月營收/採用IFRSs後每月營業收入彙總表](https://mops.twse.com.tw/mops/web/t21sc04_ifrs)頁面
* 輸入營業收入年度及月份
* 找到 csv 檔案的下載網址 (https://mops.twse.com.tw/nas/t21/sii/t21sc03_年_月.csv)
* 使用 pandas 套件下載及讀取資料
* 將資料經適當的處理 (刪除資料、條件式過濾...等)
* 儲存為 csv 檔案
* 儲存至資料庫

In [1]:
# 輸入月營收年度及月份

year = input('請輸入民國年度（譬如:109）：')
month = input('請輸入月份（譬如:2）：')

請輸入民國年度（譬如:109）：109
請輸入月份（譬如:2）：2

In [37]:
# 擷取資料

import pandas as pd

try:
    url = 'https://mops.twse.com.tw/nas/t21/sii/t21sc03_'+year+'_'+month+'.csv'
    #df = pd.read_csv(url)
    df = pd.read_csv('g3a-t21sc03_109_2.csv', encoding='utf-8-sig')
except Exception as e:
    print('**WARRN: 擷取失敗')
    print('錯誤訊息', e)
else:
    print('成功擷取!')

成功擷取!

In [30]:
# 觀看 DataFrame 相關資訊

#df.head(10)
#df.info()   # 欄位資訊
#df.columns  # 欄位名稱
df.dtypes   # 欄位型別
#df.shape    # 列數及欄數
#df.describe()   # 各項統計資訊

出表日期                 object
資料年月                 object
公司代號                  int64
公司名稱                 object
產業別                  object
營業收入-當月營收             int64
營業收入-上月營收             int64
營業收入-去年當月營收           int64
營業收入-上月比較增減(%)      float64
營業收入-去年同月增減(%)      float64
累計營業收入-當月累計營收         int64
累計營業收入-去年累計營收         int64
累計營業收入-前期比較增減(%)    float64
備註                   object
dtype: object

In [38]:
# 轉換欄位的資料型別

df = df.astype({'公司代號': 'str'})
df.dtypes

出表日期                 object
資料年月                 object
公司代號                 object
公司名稱                 object
產業別                  object
營業收入-當月營收             int64
營業收入-上月營收             int64
營業收入-去年當月營收           int64
營業收入-上月比較增減(%)      float64
營業收入-去年同月增減(%)      float64
累計營業收入-當月累計營收         int64
累計營業收入-去年累計營收         int64
累計營業收入-前期比較增減(%)    float64
備註                   object
dtype: object

In [39]:
# 刪除欄資料及欄名稱更名

df.drop('出表日期', axis=1, inplace=True)   # 刪除

df.rename(columns={'營業收入-當月營收':'當月營收'}, inplace=True)
df.rename(columns={'營業收入-上月營收':'上月營收'}, inplace=True)
df.rename(columns={'營業收入-去年當月營收':'去年當月營收'}, inplace=True)
df.rename(columns={'營業收入-上月比較增減(%)':'上月比較增減'}, inplace=True)
df.rename(columns={'營業收入-去年同月增減(%)':'去年同月增減'}, inplace=True)
df.rename(columns={'累計營業收入-當月累計營收':'當月累計營收'}, inplace=True)
df.rename(columns={'累計營業收入-去年累計營收':'去年累計營收'}, inplace=True)
df.rename(columns={'累計營業收入-前期比較增減(%)':'前期比較增減'}, inplace=True)

df.head(5)

,資料年月,公司代號,公司名稱,產業別,當月營收,上月營收,去年當月營收,上月比較增減,去年同月增減,當月累計營收,去年累計營收,前期比較增減,備註
0,109/2,1101,台泥,水泥工業,5000692,7502141,5085162,-33.343135,-1.661107,12502833,14479402,-13.650902,-
1,109/2,1102,亞泥,水泥工業,2851105,5210319,3165899,-45.279646,-9.943274,8061424,11071636,-27.188502,-
2,109/2,1103,嘉泥,水泥工業,150813,165029,108448,-8.614244,39.064805,315842,285508,10.624571,-
3,109/2,1104,環泥,水泥工業,414075,359966,270638,15.031697,52.999579,774041,750157,3.183867,108年2月適逢農曆春節，工作天數較少。
4,109/2,1108,幸福,水泥工業,390288,296395,168065,31.678335,132.224437,686683,521254,31.736735,因去年同期適逢農曆春節假期發貨天數較少外，本月因部分同業設備維修出貨量下降，惟整體市場需求上...

In [40]:
# 設定索引

df.set_index(['資料年月','公司代號'], inplace=True)
df.head(5)

           公司名稱   產業別     當月營收     上月營收   去年當月營收     上月比較增減      去年同月增減  \
資料年月  公司代號
109/2 1101   台泥  水泥工業  5000692  7502141  5085162 -33.343135   -1.661107
      1102   亞泥  水泥工業  2851105  5210319  3165899 -45.279646   -9.943274
      1103   嘉泥  水泥工業   150813   165029   108448  -8.614244   39.064805
      1104   環泥  水泥工業   414075   359966   270638  15.031697   52.999579
      1108   幸福  水泥工業   390288   296395   168065  31.678335  132.224437

              當月累計營收    去年累計營收     前期比較增減  \
資料年月  公司代號
109/2 1101  12502833  14479402 -13.650902
      1102   8061424  11071636 -27.188502
      1103    315842    285508  10.624571
      1104    774041    750157   3.183867
      1108    686683    521254  31.736735

                                                           備註
資料年月  公司代號
109/2 1101                                                  -
      1102                                                  -
      1103                                                  -
      1104                               108年2月適逢農曆春節，工作天數較少。
      1108  因去年同期適逢農曆春節假期發貨天數較少外，本月因部分同業設備維修出貨量下降，惟整體市場需求上...

# 寫入 csv 檔案

In [26]:
filename = '營業收入-'+ year + month +'.csv'
df.to_csv(filename, encoding='utf-8-sig')
print('寫入完畢!')

寫入完畢!

# SQLite 資料庫

SQLite：一種檔案型式的資料庫，[官方網站](https://www.sqlite.org/index.html)

DB Browser for SQLite：讀取及操作 SQLite 工具軟體，[官方網站](https://sqlitebrowser.org/)

Python 操作 SQLite 教學：[英文教學網站](https://sebastianraschka.com/Articles/2014_sqlite_in_python_tutorial.html)

In [41]:
import sqlite3

# 建立資料庫連結
conn = sqlite3.connect('stock.db')  # or stock.sqlite3

# 寫入資料庫
df.to_sql('monthly', conn, if_exists='replace')

print('寫入完畢!')

寫入完畢!

# 讀取資料庫

SQL 語法：

    select "欄位名稱" from "表格名稱" where 條件式

In [54]:
# 讀取資料庫

sqlstr = 'select * from monthly'
#sqlstr = 'select 公司代號,公司名稱,上月比較增減,前期比較增減 from monthly'
#sqlstr = 'select * from monthly where 公司代號 in ("1101","2317","2330")'
monthly = pd.read_sql(sqlstr, conn, index_col='公司代號')
monthly.head(5)

,資料年月,公司名稱,產業別,當月營收,上月營收,去年當月營收,上月比較增減,去年同月增減,當月累計營收,去年累計營收,前期比較增減,備註
公司代號,,,,,,,,,,,,
1101,109/2,台泥,水泥工業,5000692,7502141,5085162,-33.343135,-1.661107,12502833,14479402,-13.650902,-
1102,109/2,亞泥,水泥工業,2851105,5210319,3165899,-45.279646,-9.943274,8061424,11071636,-27.188502,-
1103,109/2,嘉泥,水泥工業,150813,165029,108448,-8.614244,39.064805,315842,285508,10.624571,-
1104,109/2,環泥,水泥工業,414075,359966,270638,15.031697,52.999579,774041,750157,3.183867,108年2月適逢農曆春節，工作天數較少。
1108,109/2,幸福,水泥工業,390288,296395,168065,31.678335,132.224437,686683,521254,31.736735,因去年同期適逢農曆春節假期發貨天數較少外，本月因部分同業設備維修出貨量下降，惟整體市場需求上...

# 營收相關操作

In [58]:
# 找出營收成長股

df[df['上月比較增減'] > 10]
#df[df['去年同月增減'] > 10]
#df1 = df[(df['上月比較增減'] > 10) & (df['去年同月增減'] > 10)]
#df1

            公司名稱   產業別     當月營收     上月營收   去年當月營收     上月比較增減      去年同月增減  \
資料年月  公司代號
109/2 1104    環泥  水泥工業   414075   359966   270638  15.031697   52.999579
      1108    幸福  水泥工業   390288   296395   168065  31.678335  132.224437
      1305    華夏  塑膠工業  1269527  1042016   881123  21.833734   44.080565
      1307    三芳  塑膠工業   833964   748887   692269  11.360459   20.468200
      1316    上曜  建材營造    38705    30363    34224  27.474229   13.093151
...          ...   ...      ...      ...      ...        ...         ...
      9927    泰銘    其他   776502   645871   603560  20.225556   28.653655
      9930  中聯資源    其他   897914   695196   592171  29.159834   51.630863
      9938    百和    其他  1499752   958811  1338991  56.417897   12.006130
      9945   潤泰新    其他  1373005  1168710   850381  17.480384   61.457629
      9958   世紀鋼  鋼鐵工業   467060   331666   121790  40.822394  283.496182

             當月累計營收   去年累計營收      前期比較增減  \
資料年月  公司代號
109/2 1104   774041   750157    3.183867
      1108   686683   521254   31.736735
      1305  2311543  2074359   11.434086
      1307  1582851  1602944   -1.253506
      1316    69068    85891  -19.586453
...             ...      ...         ...
      9927  1422373  1389567    2.360879
      9930  1593110  1613222   -1.246698
      9938  2458563  2603484   -5.566426
      9945  2541715  2243619   13.286391
      9958   798726   221675  260.313973

                                                           備註
資料年月  公司代號
109/2 1104                               108年2月適逢農曆春節，工作天數較少。
      1108  因去年同期適逢農曆春節假期發貨天數較少外，本月因部分同業設備維修出貨量下降，惟整體市場需求上...
      1305                                                  -
      1307                                                  -
      1316                                                  -
...                                                       ...
      9927                                                  -
      9930          本月營收較去年同期增加51.63%，主因108年2月適逢春節假期工作天數減少所致。
      9938                                                  -
      9945         主係本公司建案交屋認列及子公司潤弘業務正於大量施工階段，以致本月營收較去年同期增加。
      9958              本月及本年增加百分比達50%以上，主因風力事業陸續投產，影響收入較同期增加

[119 rows x 11 columns]

In [59]:
# 依產業別計算營收成長家數

df1.groupby('產業別').count()

          公司名稱  當月營收  上月營收  去年當月營收  上月比較增減  去年同月增減  當月累計營收  去年累計營收  前期比較增減  備註
產業別
光電業          4     4     4       4       4       4       4       4       4   4
其他           9     9     9       9       9       9       9       9       9   9
其他電子業        3     3     3       3       3       3       3       3       3   3
化學工業         5     5     5       5       5       5       5       5       5   5
半導體業        15    15    15      15      15      15      15      15      15  15
塑膠工業         5     5     5       5       5       5       5       5       5   5
建材營造        17    17    17      17      17      17      17      17      17  17
橡膠工業         3     3     3       3       3       3       3       3       3   3
水泥工業         2     2     2       2       2       2       2       2       2   2
汽車工業         2     2     2       2       2       2       2       2       2   2
油電燃氣業        1     1     1       1       1       1       1       1       1   1
玻璃陶瓷         1     1     1       1       1       1       1       1       1   1
生技醫療業        7     7     7       7       7       7       7       7       7   7
紡織纖維         9     9     9       9       9       9       9       9       9   9
資訊服務業        2     2     2       2       2       2       2       2       2   2
通信網路業        2     2     2       2       2       2       2       2       2   2
造紙工業         3     3     3       3       3       3       3       3       3   3
金融保險業        2     2     2       2       2       2       2       2       2   2
鋼鐵工業         8     8     8       8       8       8       8       8       8   8
電器電纜         6     6     6       6       6       6       6       6       6   6
電子通路業        2     2     2       2       2       2       2       2       2   2
電子零組件業       5     5     5       5       5       5       5       5       5   5
電機機械         4     4     4       4       4       4       4       4       4   4
電腦及週邊設備業     2     2     2       2       2       2       2       2       2   2